---
apiVersion: v1
kind: Service
metadata:
  name: kafka-external-service
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - port: 9094
    nodePort: 32094
    name: external
    protocol: TCP
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-internal-service
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
  - port: 9092
    protocol: TCP
    name: internal
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cs
  labels:
    app: kafka
spec:
  ports:
  - port: 9093
    name: inter
  selector:
    app: kafka
---
