---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-broker1
spec:
  template:
    metadata:
      labels:
        app: kafka
        id: "1"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        - containerPort: 9094
        env:
        - name: HOSTNAME_COMMAND
          value: curl http://169.254.169.254/latest/meta-data/public-hostname
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
        - name: KAFKA_LISTENERS
          value: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: RACK_COMMAND
          value: curl http://169.254.169.254/latest/meta-data/placement/availability-zone
        # - name: KAFKA_BROKER_ID
        #   value: "1"
