---
apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: zk-cs
#   labels:
#     app: zk
#     name: zk-cs
# spec:
#   type: NodePort
#   ports:
#   - port: 2181
#     nodePort: 32081
#     name: client
#     protocol: TCP
#   selector:
#     app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk
---
