---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongo-sc
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: mongo-pv-type
spec:
  storageClassName: mongo-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-084951a6921c94348
    fsType: ext4
---
# if using kops, automatically provision EBS storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
spec:
  storageClassName: mongo-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
