apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: {{.clusterName}}
  name: {{.name}}
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: {{.machineType}}
  maxSize: {{.maxSize}}
  minSize: {{.minSize}}
  nodeLabels:
    kops.k8s.io/instancegroup: {{.name}}
  role: Node
  subnets:
    - {{.awsRegion}}a
